const SET_STUDENTLIST = 'SET_STUDENTLIST';
const SET_STUDENTGENDERTYPE = 'SET_STUDENTGENDERTYPE';
const SET_ENTER = 'SET_ENTER';
const ADD_STUDENT = 'ADD_STUDENT';
const SET_ISLOADING = 'SET_ISLOADING';
const SET_STUDENTNAME = 'SET_STUDENTNAME';

const actionTypes = {
  SET_STUDENTLIST,
  SET_STUDENTGENDERTYPE,
  SET_ENTER,
  ADD_STUDENT,
  SET_ISLOADING,
  SET_STUDENTNAME
};

module.exports = actionTypes;
